### ISSUE TITLE
Add an enum for use in place of `request_block_annotations: bool`

### ISSUE THREAD

**Issue by sunfishcode** [bytecodealliance/regalloc.rs#42]
Several functions in this crate take a bool parameter for `request_block_annotations`, including `allocate_registers` which is part of the crate API. While callers can add comments to parameters to help remind readers what bool parameters mean at the callsites, it would help clarify the code to introduce an `enum` type which describes the options and use that instead of `bool`.

This would also resolve https://github.com/bytecodealliance/wasmtime/pull/1494/files#r406665710 in a nice way.

**Comment by bnjbvr** [comment]
I think using plain options as proposed in #31 will make this very explicit without having to use an enum.

**Comment by bnjbvr** [comment]
Fixed by 3083ffb.
